#sharding:
#  jdbc:
#    datasource:
#      names: ds_0,ds_1
#      ds_0:
#        type: org.apache.commons.dbcp.BasicDataSource
#        driver-class-name:
#        url:
#        username:
#        password:
#      ds_1:
#        type: org.apache.commons.dbcp.BasicDataSource
#        driver-class-name:
#        url:
#        username:
#        password:
#    config:
#     sharding:
#      default-database-strategy:
#       inline:
#        sharding-column: user_id
#        algorithm-expression: ds_$->{user_id % 2}
#      tables:
#       t_order:
#        actual-data-nodes: ds_$->{0..1}.t_order_$->{0..1}
#        table-strategy:
#          inline:
#           sharding-column: order_id
#           algorithm-expression: t_order_$->{order_id % 2}
#        key-generator-column-name: order_id
#       t_order_item:
#        actual-data-nodes: ds_$->{0..1}.t_order_item_$->{0..1}
#        table-strategy:
#          inline:
#           sharding-column: order_id
#           algorithm-expression: t_order_item_$->{order_id % 2}
#        key-generator-column-name: order_item_id