### Core \u8bbe\u7f6e
spring:
  main:
     banner-mode: "off"
  http:
    encoding:
     charset: UTF-8
     enabled: true
     force: true
  profiles:
   active: prod
  messages:
    encoding: UTF-8
  freemarker:
    prefix:
    suffix: .ftl
    templateLoaderPath: classpath:/templates/tpl/
    templateEncoding: UTF-8
    prefer-file-system-access: false
    cache: false
    settings:
      template_update_delay: 0
    request-context-attribute: request
info:
  app-name: \u5f00\u53d1\u73af\u5883
  app-description: ${info.app-name} \u63cf\u8ff0
  app-version:
#######maven pom \u91cc\u7684\u914d\u7f6e
server:
  port: 9080
management:
  contextPath: /admin/monitor
  security:
    enabled: false