server:
  compression:
   enabled: true
logging:
  path: /var/www/logs
  config: classpath:logback-spring.xml
spring:
  output:
    ansi:
      enabled: DETECT
  mail:
    host: smtp.163.com
    username: lkg61230413@163.com
    password: lkg186681
    from: GG<lkg61230413@163.com>
    template-path: classpath:/templates/email/
    properties:mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
      debug: true
  datasource:
    url: jdbc:mysql://ss.itaobao.pub:3306/lore-test?Unicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: omw@178.Im
   # validation-query: SELECT 1
    min-idle: 10
    max-active: 20
    driverClassName: com.mysql.jdbc.Driver
    druid:
      logSlowSql: false
      mergeSql: true
      slowSqlMillis: 3000
  jpa:
  # Specify the DBMS
    database: MYSQL
  # Show or not log for each sql query
    show-sql: true
    open-in-view: true
    hibernate:
     show_sql: true
     format_sql: true
     # Hibernate ddl auto (create, create-drop, update)
     ddl-auto: none
     # Naming strategy
     naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
     # stripped before adding them to the entity manager)
    properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
       enable_lazy_load_no_trans: true
  data:
    elasticsearch:
      cluster-name: elasticsearch #节点名字，默认elasticsearch
      cluster-nodes: 127.0.0.1:9200 #节点地址，多个节点用逗号隔开
      local: false
      repositories:
        enable: true
      properties:
        path:
          logs: ./var/log/elasticsearch #elasticsearch日志存储目录
          data: /var/elasticsearch/data #elasticsearch数据存储目录
